StartTime = ""
EndTime = ""
LogGroupName = ""
LogQuery = """"""
AWSRegion = ""

# sample config
# StartTime = "2020-12-01T12:59:59"
# EndTime = "2020-12-05T12:59:59" 
# LogGroupName = "TempLogGroup"
# LogQuery = """fields @timestamp, @message
#| sort @timestamp desc
#| limit 20"""
# AWSRegion = "us-east-1"

