StartTime = "2023-10-18T00:00:00"
EndTime = "2023-10-18T23:59:59"
LogGroupName = "/dev-use1-catalog-search-service/service"
LogQuery = """fields @timestamp, @log
| filter @message like /batchEvaluateFeatureResponse/
| parse @message "Results=[*])" as Evaluation_Results
| sort @timestamp desc"""
AWSRegion = "us-east-1"