StartTime = "2023-10-23T00:00:00"
EndTime = "2023-10-23T23:59:59"
LogGroupName = "/prd-use1-catalog-search-service/service"
LogQuery = """fields @timestamp, @log
| filter @message like /batchEvaluateFeatureResponse/
| filter @message like /2023_10_Cornucopia2_5/
| parse @message "Results=[*])" as Evaluation_Results
| sort @timestamp desc"""
AWSRegion = "us-east-1"